### PR TITLE
fix(windows-agent): Avoid panic in distro properties

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
This PR fixes a race where unregistering a distro at a very unfortunate time would cause a panic.

From [LBYL](https://docs.python.org/3.5/glossary.html#term-lbyl) to [EAFP](https://docs.python.org/3.5/glossary.html#term-eafp) 😃

---

UDENG-2385

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
For some reason CI is not running 🤷

**Comment by EduardGomezEscandell** [comment]
Force-pushed to trigger CI, no changes.

**Comment by EduardGomezEscandell** [comment]
Regarding codecov: I don't think we need to test a panic 🙃

**Review by didrocks — APPROVED** [review]
With current tests still passing, and I agree there is no need to test the panic, so +1! Good work :)

**Pull request merged**
