### PR TITLE
docs: add landing pages and start content restructure

### PR DESCRIPTION
**Pull request by edibotopic**
This marks the start of a content restructure for the UP4W documentation.

The **major** changes include:

* **Landing pages** are added for each Diataxis section with text guiding the user through the contents, with the embedded TOC divided into sub-sections. Landing pages will need to be revisited when/if new content is added.
* **Sub-sections** are added where individual Ditaxis sections contain multiple doc pages spanning different topics
* **Developer documentation** is incorporated directly into the main documentation (`how-to guides>contributing to UP4W` and `reference>debugging and testing`)
* **Generic, small pages relating to other software** (WSL, Landscape, Ubuntu WSL) are removed and replaced with external links to the relevant documentation (see "supporting technologies" in `reference>UP4W components`)
* **Deletion** of the guide outlining how to set up landscape server on WSL; this does not serve an obvious user need currently and does not have an suitable place in the documentation)

Some planned changes are **out of scope** for this PR:

* A Diataxis Explanation section will be added in a future PR to accommodate content relating to -- at a minimum -- UP4W architecture. At that point, material in `reference>UP4W components` may be consolidated further.
* Some content, including the guide `back up and restore ubuntu WSL instances` may be a better fit for the Ubuntu WSL docs and will be considered as part of separate work aimed at restructuring those docs.
* The styling of the landing pages could be improved. The top-level bullet for each sub-section is not needed but removing this requires changing how the toc-trees are included on each page. When these are removed, headers will be added to more clearly distinguish the sections.

During the restructure there were some minor changes to wording and links.

UDENG-5304

### CODE REVIEW

**Review by CarlosNihelton — COMMENTED** [review]
Impressive work. I have some comments for your consideration. Let me know your thoughts.

**Comment by edibotopic** [comment]
Thanks a lot for the review @CarlosNihelton -- good spots!!!

I might carry this PR into the next pulse so that we can discuss before finalising.

**Review by CarlosNihelton — APPROVED** [review]
Let's address my comments in subsequent PRs as we've discussed.

**Comment by edibotopic** [comment]
> Let's address my comments in subsequent PRs as we've discussed.

Got it. I will resolve the conversations and return to those points in that PR.

**Pull request merged**
